# Generated by Django 5.0.6 on 2024-08-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_identify',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
