# Generated by Django 5.0.6 on 2024-07-13 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_video', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='sentence',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='sentencequiz',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='wordquiz',
            options={'managed': True},
        ),
    ]
