# Generated by Django 5.0.6 on 2024-07-13 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_video', '0003_quiz_user_quiz_video_sentence_video_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordquiz',
            options={},
        ),
        migrations.AlterModelTable(
            name='wordquiz',
            table=None,
        ),
    ]
