# Generated by Django 5.0.6 on 2024-07-13 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_video', '0004_alter_wordquiz_options_alter_wordquiz_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sentence',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sentencequiz',
            options={},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={},
        ),
        migrations.AlterModelTable(
            name='quiz',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sentence',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sentencequiz',
            table=None,
        ),
        migrations.AlterModelTable(
            name='test',
            table=None,
        ),
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
        migrations.AlterModelTable(
            name='video',
            table=None,
        ),
        migrations.AlterModelTable(
            name='word',
            table=None,
        ),
    ]
