# Generated by Django 5.0.6 on 2024-07-13 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_video', '0005_alter_quiz_options_alter_sentence_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='quiz',
            table='quiz',
        ),
    ]
