# Generated by Django 5.0.6 on 2024-07-13 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_video', '0006_alter_quiz_options_alter_quiz_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentence',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='quiz',
            table=None,
        ),
    ]
