# Generated by Django 5.0.6 on 2024-07-13 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_video', '0007_alter_sentence_options_alter_quiz_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
    ]
