# Generated by Django 5.0.6 on 2024-07-13 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_video', '0008_alter_quiz_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentence',
            options={},
        ),
    ]
