# Generated by Django 5.0.6 on 2024-07-13 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_video', '0010_alter_quiz_table_alter_sentence_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='video',
        ),
        migrations.RemoveField(
            model_name='wordquiz',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='sentencequiz',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='video',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RemoveField(
            model_name='video',
            name='user',
        ),
        migrations.RemoveField(
            model_name='word',
            name='video',
        ),
        migrations.DeleteModel(
            name='WordQuiz',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='SentenceQuiz',
        ),
        migrations.DeleteModel(
            name='Sentence',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
