# Generated by Django 5.0.6 on 2024-07-13 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_video', '0011_remove_quiz_user_remove_quiz_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_date', models.DateTimeField(blank=True, null=True)),
                ('answer_per', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'quiz',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'test',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('passwd', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='SentenceQuiz',
            fields=[
                ('sentence_quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_0', models.JSONField(blank=True, db_column='quiz', null=True)),
                ('is_wrong', models.IntegerField(blank=True, null=True)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_video.quiz')),
            ],
            options={
                'db_table': 'sentence_quiz',
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_video.users', to_field='user_id'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('save_date', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.IntegerField(blank=True, null=True)),
                ('img', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_video.users', to_field='user_id')),
            ],
            options={
                'db_table': 'video',
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('sentence_id', models.AutoField(primary_key=True, serialize=False)),
                ('sentence_eg', models.CharField(blank=True, max_length=500, null=True)),
                ('sentence_kr', models.CharField(blank=True, max_length=500, null=True)),
                ('save_date', models.DateTimeField(blank=True, null=True)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_video.video')),
            ],
            options={
                'db_table': 'sentence',
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_video.video'),
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False)),
                ('word_eg', models.CharField(blank=True, max_length=500, null=True)),
                ('word_kr', models.CharField(blank=True, max_length=500, null=True)),
                ('save_date', models.DateTimeField(blank=True, null=True)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_video.video')),
            ],
            options={
                'db_table': 'word',
            },
        ),
        migrations.CreateModel(
            name='WordQuiz',
            fields=[
                ('word_quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_0', models.JSONField(blank=True, db_column='quiz', null=True)),
                ('is_wrong', models.IntegerField(blank=True, null=True)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_video.quiz')),
            ],
            options={
                'db_table': 'word_quiz',
            },
        ),
    ]
