# Generated by Django 5.0.6 on 2024-08-19 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_video', '0012_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='state',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='answer_per',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_date',
            field=models.DateTimeField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='user',
            field=models.ForeignKey(default='user1', on_delete=django.db.models.deletion.CASCADE, to='app_video.users', to_field='user_id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='video',
            field=models.ForeignKey(default='https://www.youtube.com/watch?v=fwURtkiXwyk', on_delete=django.db.models.deletion.CASCADE, to='app_video.video'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(default='test@gmail.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='passwd',
            field=models.CharField(default='user1', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
