# Generated by Django 5.0.6 on 2024-08-19 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_video', '0014_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_video.authuser'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_video.authuser'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
